language: android
android:
  components:
    - build-tools-22.0.1 # Specify your build tools verison
    - android-22 # Android Platform Target
env: # Environment Variables
cache:
  directories:
    - node_modules
global:
before_install:
# Commands to excecute before install
- echo "Before install stage"
install:
# Specify what and how to install
- echo "Install stage"
- sudo apt-get install -y python-software-properties
- curl --silent --location https://deb.nodesource.com/setup_8.x | sudo -E bash -
- sudo apt-get install -y nodejs
- sudo npm install -g cordova
#- sudo npm i
before_script:
# Commands to excecute before running tests
- echo "Before script stage"
script:
# Run tests
- echo "Running tests"
- npm test
- echo "Starting build"
- npm run build
after_success:
# You can do thing after success
- echo "Build success"
after_failure:
# What if your test fails?
- echo "After failure stage"
after_script:
# Do things anyway after script/test pass or not
- echo "After script stage"
